### ISSUE TITLE
Expanding the docs.

### ISSUE THREAD

**Issue by aleeusgr** [winston0410/mkNodePackage#1]
Hi!
I am relatively new to nix, my task is to port a node project to nix.

I don't understand the usage example.
Should I copy paste this code in a file and run `nix build`?

Can you recommend any docs on how to use mkNodePackage?

thank you.

**Comment by winston0410** [comment]
Hiya, I think you will need to change the `src` attribute to a local directory. But I havn't used this module a while myself as well, so I am not 100% sure too
